/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.elibrary_project.gui;

import com.mycompany.elibrary_project.model.Book;
import com.mycompany.elibrary_project.model.Borrow;
import com.mycompany.elibrary_project.model.Member;
import com.mycompany.elibrary_project.model.Staff;
import com.mycompany.elibrary_project.service.BookService;
import com.mycompany.elibrary_project.service.BorrowService;
import com.mycompany.elibrary_project.service.MemberService;
import com.mycompany.elibrary_project.service.StaffService;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class NewBorrowFrame extends javax.swing.JFrame {

    private BookService bookService;
    private MemberService memberService;
    private StaffService staffService;
    private BorrowService borrowService;

    /**
     * Creates new form NewBorrowFrame
     */
    public NewBorrowFrame(BookService bookService, MemberService memberService, StaffService staffService, BorrowService borrowService) {
        initComponents();
        this.bookService = bookService;
        this.memberService = memberService;
        this.staffService = staffService;
        this.borrowService = borrowService;
        showBookComboData();
        showMemberComboData();
        showStaffComboData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clearBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bookCmb = new javax.swing.JComboBox<>();
        memberCmb = new javax.swing.JComboBox<>();
        staffCmb = new javax.swing.JComboBox<>();
        saveBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        dateCmb = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Book");

        jLabel3.setText("Member");

        jLabel4.setText("Staff");

        bookCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Book" }));
        bookCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookCmbActionPerformed(evt);
            }
        });

        memberCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Member" }));

        staffCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Staff" }));

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        jLabel5.setText("Date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateCmb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(memberCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(staffCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bookCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memberCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(staffCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookCmbActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        try {
            // Retrieve selected items from combo boxes and date picker
            Book selectedBook = (Book) bookCmb.getSelectedItem();
            Member selectedMember = (Member) memberCmb.getSelectedItem();
            Staff selectedStaff = (Staff) staffCmb.getSelectedItem();
            Date selectedDate = (Date) dateCmb.getDate();

            // Check if any of the fields are empty or invalid
            if (selectedBook == null || selectedMember == null || selectedStaff == null
                    || selectedBook.getId() == null || selectedMember.getId() == null || selectedStaff.getId() == null) {
                JOptionPane.showMessageDialog(this, "Please fill all fields!", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Check if the date is valid (not null)
            if (selectedDate == null) {
                JOptionPane.showMessageDialog(this, "Please select a borrow date!", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Create the Borrow object and set the properties
            Borrow borrow = new Borrow();
            borrow.setBook(selectedBook);
            borrow.setMember(selectedMember);
            borrow.setStaff(selectedStaff);
            borrow.setBorrowDate(selectedDate);
            borrow.setActive(1); // Assuming 1 means active in your system

            // Call the service to add the borrow record
            borrowService.addBorrow(borrow);

            // Show success message
            JOptionPane.showMessageDialog(this, "Borrow has been successfully added!");
            this.dispose(); // Close the frame after saving

        } catch (NullPointerException ex) {
            // Handle specific null pointer exception, if needed
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: Missing required fields!", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            // Catch any other exceptions
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error while adding borrow!", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_saveBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        bookCmb.setSelectedIndex(0);  
        memberCmb.setSelectedIndex(0); 
        staffCmb.setSelectedIndex(0);  
        dateCmb.setDate(null); 
    }//GEN-LAST:event_clearBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bookCmb;
    private javax.swing.JButton clearBtn;
    private com.toedter.calendar.JDateChooser dateCmb;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> memberCmb;
    private javax.swing.JButton saveBtn;
    private javax.swing.JComboBox<String> staffCmb;
    // End of variables declaration//GEN-END:variables

    private void showBookComboData() {
        try {
            DefaultComboBoxModel bookCombo = new DefaultComboBoxModel();
            bookCmb.setModel(bookCombo);
            bookCombo.addElement("Select Book");
            List<Book> bookList = bookService.getBookList();

            for (Book book : bookList) {
                bookCombo.addElement(book);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void showMemberComboData() {
        try {
            DefaultComboBoxModel memberCombo = new DefaultComboBoxModel();
            memberCmb.setModel(memberCombo);
            memberCombo.addElement("Select Member");
            List<Member> memberList = memberService.getMemberList();

            for (Member member : memberList) {
                memberCombo.addElement(member);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void showStaffComboData() {
        try {
            DefaultComboBoxModel staffCombo = new DefaultComboBoxModel();
            staffCmb.setModel(staffCombo);
            staffCombo.addElement("Select Staff");
            List<Staff> staffList = staffService.getStaffList();

            for (Staff staff : staffList) {
                staffCombo.addElement(staff);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
